language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
os:
  - linux
dist: trusty
sudo: false
osx_image: xcode8.3
env: IMPRESS_MODE=test
services:
  - mongodb
install:
  - npm install
  - npm install mongodb@2
script:
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/unittests.js
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/integration.js
  - npm run lint
