'use strict';

var config = {
  sessions: {
    characters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
    secret:     'secret',
    length:     64
  }
};

var methodConteiner = {};
methodConteiner.method = function(obj) {
  obj.field = 'value';
  return obj;
};

impress.test({
  'api.impress.falseness': [ [ [], false ] ],
  'api.impress.trueness': [ [ [], true ] ],
  'api.impress.emptyness': [ [ [], undefined ] ],
  'api.impress.localIPs': [
    [ [], function(value) { return Array.isArray(value); } ],
  ],
  'api.impress.generateSID': [
    [ config, function(result) { return result.length === 64; } ],
  ],
  'api.impress.crcSID': [
    [ config, api.impress.generateKey(config.sessions.length - 4, config.sessions.characters), function(result) {
      return result.length === 4;
    } ]
  ],
  'api.impress.validateSID': [
    [ config, 'ag0DEZqImmOPOQxl1DCIJh5KvSr4OX6wE2tDoVybqNrs1jLhimN7zV6mCPyl5b96', true  ],
    [ config, 'ag0DEZqImmOfOQxl1DCIJh5KvSr4OX6wE2tDoVybqNrs1jLhimN7zV6mCPyl5b96', false ],
    [ config, '2XpU8oAewXwKJJSQeY0MByY403AyXprFdhB96zPFbpJxlBqHA3GfBYeLxgHxBhhZ', false ],
    [ config, 'WRONG-STRING', false ],
    [ config, '',             false ],
  ],
  'api.impress.subst': [
    [ 'Hello, @name@',  { name:'Ali' }, '', true,                   'Hello, Ali' ],
    [ 'Hello, @.name@', { person: { name:'Ali' } }, 'person', true, 'Hello, Ali' ],
  ],
  'api.impress.getByPath': [
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.value',            'Gagarin' ],
    [ { item: { subitem: { value: 123       } } }, 'item.subitem.value',                  123 ],
    [ { item: { subitem: { value: true      } } }, 'item.subitem.value',                 true ],
    [ { item: { subitem: { value: false     } } }, 'item.subitem.value',                false ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.none',             undefined ],
    [ { item: { subitem: { value: null      } } }, 'item.subitem.value',                 null ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.none.value',               undefined ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem',       { value: 'Gagarin' } ],
  ],
  'api.impress.setByPath': [
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.value', 'Gagarin',             true ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.none',  'Gagarin',             true ],
    [ { item: { subitem: { value: 123       } } }, 'item.subitem.value', 123,                   true ],
    [ { item: { subitem: { value: true      } } }, 'item.subitem.value', true,                  true ],
    [ { item: { subitem: { value: false     } } }, 'item.subitem.value', false,                 true ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.none',  undefined,             true ],
    [ { item: { subitem: { value: null      } } }, 'item.subitem.value', null,                  true ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.none.value',    undefined,            false ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'none.value',         123,                  false ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem',       { value: 'Gagarin' },  true ],
  ],
  'api.impress.deleteByPath': [
    [ { item: { surname: 'Gagarin', name: 'Yuri' } }, 'item.name',    true ],
    [ { item: { surname: 'Gagarin', name: 'Yuri' } }, 'item.noname', false ],
    [ { item: { surname: 'Gagarin', name: 'Yuri' } }, 'item',         true ],
    [ { item: { surname: 'Gagarin', name: 'Yuri' } }, 'unknown',     false ],
  ],
  'api.impress.htmlEscape': [
    [ 'text',                         'text' ],
    [ '<tag>',                 '&lt;tag&gt;' ],
    [ 'You &amp; Me',     'You &amp;amp; Me' ],
    [ 'You & Me',             'You &amp; Me' ],
    [ '"Quotation"', '&quot;Quotation&quot;' ],
  ],
  'api.impress.fileExt': [
    [ '/dir/dir/file.txt', 'txt' ],
    [ '/dir/dir/file.txt', 'txt' ],
    [ '\\dir\\file.txt',   'txt' ],
    [ '/dir/dir/file.txt', 'txt' ],
    [ '/dir/file.txt',     'txt' ],
    [ '/dir/file.TXt',     'txt' ],
    [ '//file.txt',        'txt' ],
    [ 'file.txt',          'txt' ],
    [ '/dir.ext/',         'ext' ],
    [ '/dir/',             ''    ],
    [ '/',                 ''    ],
    [ '.',                 ''    ],
    [ '',                  ''    ],
  ],
  'api.impress.isTimeEqual': [
    [ '2014-01-01', '2014-01-01',  true ],
    [ '2014-01-01', '2014-01-02', false ],
    [ '1234-12-12', '1234-12-12',  true ],
    [ '1234-12-12', '4321-12-21', false ],
  ],
  'api.impress.parseHost': [
    [ '',                'no-host-name-in-http-headers' ],
    [ 'domain.com',      'domain.com' ],
    [ 'localhost',       'localhost'  ],
    [ 'domain.com:8080', 'domain.com' ],
  ],
  'api.impress.removeBOM': [
    [ '\uBBBF\uFEFFabc', 'abc' ],
    [ '\uBBBF\uFEFF',    ''    ],
    [ '\uFEFFabc',       'abc' ],
    [ '\uBBBFabc',       'abc' ],
    [ '\uFEFF',          ''    ],
    [ '\uBBBF',          ''    ],
    [ 'abc',             'abc' ],
  ],
  'api.impress.arrayRegExp': [
    [ ['*'],                 '^.*$' ],
    [ ['/css/*','/folder*'], '^((\\/css\\/.*)|(\\/folder.*))$' ],
    [ ['/','/js/*'],         '^((\\/)|(\\/js\\/.*))$' ],
    [ ['/css/*.css'],        '^\\/css\\/.*\\.css$' ],
    [ ['*/css/*'],           '^.*\\/css\\/.*$' ],
  ],
  'api.impress.pad2': [
    [  0, '00' ],
    [  5, '05' ],
    [ 10, '10' ],
  ],
  'api.impress.nowDate': [
    [ new Date('2014-12-12 12:30:15.150'), '2014-12-12' ],
    [ new Date('2014-12-12 12:30:15'),     '2014-12-12' ],
    [ new Date('2014-12-12 12:30'),        '2014-12-12' ],
    [ new Date('2014-12-12'),              '2014-12-12' ],
  ],
  'api.impress.nowDateTime': [
    [ new Date('2014-12-12 12:30:15.150Z'), '2014-12-12 12:30' ],
    [ new Date('2014-12-12 12:30:15Z'),     '2014-12-12 12:30' ],
    [ new Date('2014-12-12 12:30Z'),        '2014-12-12 12:30' ],
    [ new Date('2014-12-12Z'),              '2014-12-12 00:00' ],
  ],
  'api.impress.sortCompareConfig': [
    [ 'files.js', 'sandbox.js',       1 ],
    [ 'filestorage.js', 'routes.js', -1 ],
    [ 'unknown.js', 'sandbox.js',     1 ],
    [ 'log.js', 'sandbox.js',         1 ],
    [ 'sandbox.js', 'sandbox.js',     0 ],
    [ 'log.js', 'log.js',             0 ],
    [ 'tasks.js', 'application.js',  -1 ],
  ],
  'api.impress.sortCompareDirectories': [
    [ { name: '/abc' },     { name: 'abc.ext' },  -1 ],
    [ { name: 'ABC.ext' },  { name: '/abc' },      1 ],
    [ { name: 'abc' },      { name: 'ABC.ext' },   1 ],
    [ { name: '/ABC' },     { name: '/abc.ext' }, -1 ],
    [ { name: '/abc.ext' }, { name: '/ABC' },      1 ],
    [ { name: '/abc.ext' }, { name: '/ABC' },      1 ],
    [ { name: '/ABC' },     { name: '/ABC' },      0 ],
    [ { name: 'abc.ext' },  { name: 'abc.ext' },   0 ],
    [ { name: 'abc.ext' },  { name: 'def.ext' },  -1 ],
    [ { name: 'def.ext' },  { name: 'abc.ext' },   1 ],
  ],
  'api.impress.sortCompareByName': [
    [ { name: 'abc' }, { name: 'def' },  -1 ],
    [ { name: 'def' }, { name: 'abc' },   1 ],
    [ { name: 'abc' }, { name: 'abc' },   0 ],
    [ { name: 'def' }, { name: 'def' },   0 ],
    [ { name: 'abc' }, { name: 'a' },     1 ],
    [ { name: 'a' },   { name: 'abc' },  -1 ],
    [ { name: '123' }, { name: 'name' }, -1 ],
  ],
  'api.impress.clearCacheStartingWith': [
    [ { abc: '123', abcd: '1234', abcde: '12345' }, 'abcd',               { abc: '123' } ],
    [ { abc: '123', abcd: '1234', abcde: '12345' }, 'a',                             { } ],
    [ { abc: '123', abcd: '1234' }, 'qwer',                 { abc: '123', abcd: '1234' } ],
    [ { abc: '123', abcd: '1234' }, 'abc',                                           { } ]
  ],
  'api.impress.spinalToCamel': [
    [ 'hello-world',     'helloWorld' ],
    [ 'hello_world',     'helloWorld' ],
    [ 'one-two-three',  'oneTwoThree' ],
    [ 'one_two_three',  'oneTwoThree' ],
    [ 'OneTwoThree',    'OneTwoThree' ],
    [ 'oneTwoThree',    'oneTwoThree' ],
    [ 'hello',                'hello' ],
    [ 'h',                        'h' ],
    [ '-',                         '' ],
    [ '_',                         '' ],
    [ '',                          '' ],
  ],
  'api.impress.duration': [
    [ '1d',             86400000 ],
    [ '10h',            36000000 ],
    [ '7m',               420000 ],
    [ '13s',               13000 ],
    [ '2d 43s',        172843000 ],
    [ '5d 17h 52m 1s', 496321000 ],
    [ '1s',                 1000 ],
    [ 500,                   500 ],
    [ 0,                       0 ],
    [ '',                      0 ],
    [ '15',                    0 ],
    [ '10q',                   0 ],
  ],
  'api.impress.generateKey': [
    [ 0, 'ABC', function(value) { return (value.length === 0); } ],
    [ 1, 'ABC', function(value) { return (value.length === 1); } ],
    [ 2, 'ABC', function(value) { return (value.length === 2); } ],
    [ 4, 'ABC', function(value) { return (value.length === 4); } ],
    [ 8, 'A',                                         'AAAAAAAA' ],
    [ 1, 'A',                                                'A' ],
    [ 0, 'A',                                                 '' ],
  ],
  'api.impress.generateGUID': [
    [ function(value) { return (value.length === 36); } ],
  ],
  'api.impress.ip2int': [
    [ '127.0.0.1',        2130706433 ],
    [ '10.0.0.1',          167772161 ],
    [ '192.168.1.10',    -1062731510 ],
    [ '165.225.133.150', -1511946858 ],
    [ '0.0.0.0',                   0 ],
    [ 'wrong-string',           null ],
    [ '',                 2130706433 ],
  ],
  'api.impress.escapeRegExp': [
    [ '/path/to/res?search=this.that&a=b', '\\\\/path\\\\/to\\\\/res\\\\?search=this\\\\.that&a=b' ],
    [ '/path/to/res?search=this.that',         '\\\\/path\\\\/to\\\\/res\\\\?search=this\\\\.that' ],
    [ '/path/to/res?search',                                 '\\\\/path\\\\/to\\\\/res\\\\?search' ],
    [ '/path/to/res',                                                   '\\\\/path\\\\/to\\\\/res' ],
    [ '/path',                                                                         '\\\\/path' ],
  ],
  'api.impress.escapeRegExp.specials': [
    [ function(arr) { return arr.length === 16; } ],
  ],
  'api.impress.escapeRegExp.regex': [
    [ function(rx) { return rx instanceof RegExp; } ],
  ],
  'api.impress.trailingSlash': [
    [ '/path',   '/path/' ],
    [ '/path/',  '/path/' ],
    [ '/',            '/' ],
    [ '',             '/' ],
  ],
  'api.impress.stripTrailingSlash': [
    [ '/path',   '/path' ],
    [ '/path/',  '/path' ],
    [ '/',            '' ],
    [ '',             '' ],
  ],
  'api.impress.bytesToSize': [
    [                         0, '0'      ],
    [                         1, '1'      ],
    [                       100, '100'    ],
    [                       999, '999'    ],
    [                      1000, '1 Kb'   ],
    [                      1023, '1 Kb'   ],
    [                      1024, '1 Kb'   ],
    [                      1025, '1 Kb'   ],
    [                      1111, '1 Kb'   ],
    [                      2222, '2 Kb'   ],
    [                     10000, '10 Kb'  ],
    [                   1000000, '1 Mb'   ],
    [                 100000000, '100 Mb' ],
    [               10000000000, '10 Gb'  ],
    [             1000000000000, '1 Tb'   ],
    [           100000000000000, '100 Tb' ],
    [         10000000000000000, '10 Pb'  ],
    [       1000000000000000000, '1 Eb'   ],
    [     100000000000000000000, '100 Eb' ],
    [   10000000000000000000000, '10 Zb'  ],
    [ 1000000000000000000000000, '1 Yb'   ],
  ],
  'api.impress.sizeToBytes': [
    [        0,                         0 ],
    [      '0',                         0 ],
    [      '1',                         1 ],
    [      512,                       512 ],
    [    '100',                       100 ],
    [    '999',                       999 ],
    [   '1 Kb',                      1000 ],
    [   '2 Kb',                      2000 ],
    [  '10 Kb',                     10000 ],
    [   '1 Mb',                   1000000 ],
    [ '100 Mb',                 100000000 ],
    [  '10 Gb',               10000000000 ],
    [   '1 Tb',             1000000000000 ],
    [ '100 Tb',           100000000000000 ],
    [  '10 Pb',         10000000000000000 ],
    [   '1 Eb',       1000000000000000000 ],
    [ '100 Eb',     100000000000000000000 ],
    [  '10 Zb',   10000000000000000000000 ],
    [   '1 Yb', 1000000000000000000000000 ],
  ],
  'api.impress.sizeToBytes.units': [
    [ function(obj) { return Object.keys(obj).length === 8; } ],
  ],
  'api.impress.random': [
    [  0, 10, function(result) { return (result >=  0 && result <= 10); } ],
    [  1, 10, function(result) { return (result >=  1 && result <= 10); } ],
    [ -1, 10, function(result) { return (result >= -1 && result <= 10); } ],
    [ 10, 0,  function(result) { return (result >=  0 && result <= 10); } ],
    [ 10, 10, 10 ],
  ],
  'api.impress.shuffle': [
    [ [1,2,3],   function(result) { return JSON.stringify(result.sort()) === '[1,2,3]'; }   ],
    [ ['a','b'], function(result) { return JSON.stringify(result.sort()) === '["a","b"]'; } ],
    [ [1,'a',3], function(result) { return JSON.stringify(result.sort()) === '[1,3,"a"]'; } ],
    [ [],        function(result) { return JSON.stringify(result.sort()) === '[]'; }        ],
  ],
  'api.impress.extend': [
    [ { f1:1 },                 { f1:1 } ],
    [ { f1:1 }, {},             { f1:1 } ],
    [ {}, {},                         {} ],
    [ {}, null,                       {} ],
    [ { f1:1 }, { f2:2 }, { f1:1, f2:2 } ],
    [ null, null,                   null ],
    [ null,                         null ],
    [ 'Hello' ,                  'Hello' ],
    [ 'Hello', { f2:2 },         'Hello' ],
    [ 2, 3,                            2 ],
    [ null, {},                     null ],
    [ [], { f2:2 },                   [] ],
    [ [], [],                         [] ],
    [ [], null,                       [] ],
    [ [], 'Hello', ['H','e','l','l','o'] ],
  ],
  'api.impress.clone': [
    [ {}, {} ],
    [ [], [] ],
    [ null, null ],
    [ { f1:1 }, { f1:1 } ],
    [ { f1:1 }, { f2:2 }, { f1:1, f2:2 } ],
    [ { f1:1, sub: { f2:2, a1:[1,2] } }, { f1:1, sub:{ f2:2, a1:[1,2] } } ],
    [ { f1:1, sub: { f2:2, a1:[1,2] } }, { f3:3, a2:[3,4] }, { f1:1, sub:{ f2:2, a1:[1,2] }, f3:3, a2:[3,4] } ],
  ],
  'api.impress.trim': [
    [ 'abcdef',             'abcdef' ],
    [ 'abcdef   ',          'abcdef' ],
    [ '   abcdef',          'abcdef' ],
    [ '   abcdef   ',       'abcdef' ],
    [ ' a b c d e f ', 'a b c d e f' ],
  ],
  'api.impress.ltrim': [
    [ 'abcdef',              'abcdef' ],
    [ 'abcdef   ',        'abcdef   ' ],
    [ '   abcdef',           'abcdef' ],
    [ '   abcdef   ',     'abcdef   ' ],
    [ ' a b c d e f ', 'a b c d e f ' ],
  ],
  'api.impress.rtrim': [
    [ 'abcdef',              'abcdef' ],
    [ 'abcdef   ',           'abcdef' ],
    [ '   abcdef',        '   abcdef' ],
    [ '   abcdef   ',     '   abcdef' ],
    [ ' a b c d e f ', ' a b c d e f' ],
  ],
  'api.impress.capitalize': [
    [ 'abc', 'Abc' ],
    [ 'Abc', 'Abc' ],
    [ 'aBC', 'Abc' ],
    [ 'ABC', 'Abc' ],
    [ 'a',     'A' ],
    [ ' bc', ' Bc' ],
    [ ' ',     ' ' ],
    [ '',       '' ],
    [ '+',     '+' ],
  ],
  'api.impress.lpad': [
    [ 'abc', ' ', 10, '       abc' ],
    [ 'abc', '+',  4,       '+abc' ],
    [ 'abc', '+',  1,        'abc' ],
    [ 'abc', '+',  0,        'abc' ],
    [ 'abc', '+', -1,        'abc' ],
  ],
  'api.impress.rpad': [
    [ 'abc', ' ', 10, 'abc       ' ],
    [ 'abc', '+',  4,       'abc+' ],
    [ 'abc', '+',  1,        'abc' ],
    [ 'abc', '+',  0,        'abc' ],
    [ 'abc', '+', -1,        'abc' ],
  ],
  'api.impress.between': [
    [ 'abcdefghijk', 'cd', 'h',     'efg' ],
    [ 'field="value"', '"', '"',  'value' ],
    [ 'field:"value"', '"', '"',  'value' ],
    [ 'field[value]', '[', ']',   'value' ],
    [ 'kjihgfedcba', 'cd', 'h',        '' ],
    [ 'kjihgfedcba', 'dc', 'h',        '' ],
    [ 'field="value"', '=', '=',       '' ],
    [ 'field[value]', '{', '}',        '' ],
    [ '{a:"b",c:"d"}', '"', '"',      'b' ],
  ],
  'api.impress.isScalar': [
    [ 'value1', true  ],
    [ 50,       true  ],
    [ true,     true  ],
    [ null,     false ],
    [ [],       false ],
    [ {},       false ],
    [ '',       true  ],
  ],
  'api.impress.inArray': [
    [ [1, 2, 3], 1,              true ],
    [ [1, 2, 3], 4,             false ],
    [ ['e1', 'e2', 'e3'], 'e3',  true ],
    [ ['e1', 'e2', 'e3'], 'e4', false ],
    [ [1, null, 3], null,        true ],
  ],
  'api.impress.merge': [
    [ ['a', 'b'], ['a', 'c'],       ['a', 'b', 'c'] ],
    [ ['a', 'b'], ['a', 'b'],            ['a', 'b'] ],
    [ ['b', 'c'], ['a', 'b'],       ['b', 'c', 'a'] ],
    [ ['a', 'b'], ['c', 'd'], ['a', 'b' , 'c', 'd'] ],
    [ [1, 2, 3],  [1, 2, 3],              [1, 2, 3] ],
    [ [1, 2, 3],  [4, 5, 1],        [1, 2, 3, 4, 5] ],
  ],
  'api.impress.override': [
    [
      methodConteiner,
      function method(obj) {
        obj.data++;
        return method.inherited(obj);
      },
      undefined
    ]
  ],
  'api.impress.startsWith': [
    [ 'abc', 'a',   true  ],
    [ 'abc', 'b',   false ],
    [ 'abc', 'c',   false ],
    [ 'abc', ' ',   false ],
    [ 'abc', '+',   false ],
    [ 'abc', '' ,   true  ],
    [ 'abc', 'abc', true  ],
  ],
  'api.impress.endsWith': [
    [ 'abc', 'a',   false ],
    [ 'abc', 'b',   false ],
    [ 'abc', 'c',   true  ],
    [ 'abc', ' ',   false ],
    [ 'abc', '+',   false ],
    [ 'abc', '' ,   true  ],
    [ 'abc', 'abc', true  ],
  ],
  'api.impress.contains': [
    [ 'abc', 'a',     true  ],
    [ 'abc', 'b',     true  ],
    [ 'abc', 'c',     true  ],
    [ 'abc', 'ab',    true  ],
    [ 'abc', 'bc',    true  ],
    [ 'abc', 'abc',   true  ],
    [ 'abc', 'ac',    false ],
    [ 'abc', ' ',     false ],
    [ 'abc', 'abcde', false ],
    [ 'abc', '+',     false ],
    [ 'abc', '',      true  ],
  ],
});
