'use strict';

var methodConteiner = {};
methodConteiner.method = function(obj) {
  obj.field = 'value';
  return obj;
};

api.test.case({
  'api.common.falseness': [ [ [], false ] ],
  'api.common.trueness': [ [ [], true ] ],
  'api.common.emptyness': [ [ [], undefined ] ],
  'api.common.subst': [
    [ 'Hello, @name@',  { name:'Ali' }, '', true,                   'Hello, Ali' ],
    [ 'Hello, @.name@', { person: { name:'Ali' } }, 'person', true, 'Hello, Ali' ],
  ],
  'api.common.getByPath': [
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.value',            'Gagarin' ],
    [ { item: { subitem: { value: 123       } } }, 'item.subitem.value',                  123 ],
    [ { item: { subitem: { value: true      } } }, 'item.subitem.value',                 true ],
    [ { item: { subitem: { value: false     } } }, 'item.subitem.value',                false ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.none',             undefined ],
    [ { item: { subitem: { value: null      } } }, 'item.subitem.value',                 null ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.none.value',               undefined ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem',       { value: 'Gagarin' } ],
  ],
  'api.common.setByPath': [
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.value', 'Gagarin',             true ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.none',  'Gagarin',             true ],
    [ { item: { subitem: { value: 123       } } }, 'item.subitem.value', 123,                   true ],
    [ { item: { subitem: { value: true      } } }, 'item.subitem.value', true,                  true ],
    [ { item: { subitem: { value: false     } } }, 'item.subitem.value', false,                 true ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem.none',  undefined,             true ],
    [ { item: { subitem: { value: null      } } }, 'item.subitem.value', null,                  true ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.none.value',    undefined,             true ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'none.value',         123,                   true ],
    [ { item: { subitem: { value: 'Gagarin' } } }, 'item.subitem',       { value: 'Gagarin' },  true ],
  ],
  'api.common.deleteByPath': [
    [ { item: { surname: 'Gagarin', name: 'Yuri' } }, 'item.name',    true ],
    [ { item: { surname: 'Gagarin', name: 'Yuri' } }, 'item.noname', false ],
    [ { item: { surname: 'Gagarin', name: 'Yuri' } }, 'item',         true ],
    [ { item: { surname: 'Gagarin', name: 'Yuri' } }, 'unknown',     false ],
  ],
  'api.common.htmlEscape': [
    [ 'text',                         'text' ],
    [ '<tag>',                 '&lt;tag&gt;' ],
    [ 'You &amp; Me',     'You &amp;amp; Me' ],
    [ 'You & Me',             'You &amp; Me' ],
    [ '"Quotation"', '&quot;Quotation&quot;' ],
  ],
  'api.common.fileExt': [
    [ '/dir/dir/file.txt', 'txt' ],
    [ '/dir/dir/file.txt', 'txt' ],
    [ '\\dir\\file.txt',   'txt' ],
    [ '/dir/dir/file.txt', 'txt' ],
    [ '/dir/file.txt',     'txt' ],
    [ '/dir/file.TXt',     'txt' ],
    [ '//file.txt',        'txt' ],
    [ 'file.txt',          'txt' ],
    [ '/dir.ext/',         'ext' ],
    [ '/dir/',             ''    ],
    [ '/',                 ''    ],
    [ '.',                 ''    ],
    [ '',                  ''    ],
  ],
  'api.common.isTimeEqual': [
    [ '2014-01-01', '2014-01-01',  true ],
    [ '2014-01-01', '2014-01-02', false ],
    [ '1234-12-12', '1234-12-12',  true ],
    [ '1234-12-12', '4321-12-21', false ],
  ],
  'api.common.pad2': [
    [  0, '00' ],
    [  5, '05' ],
    [ 10, '10' ],
  ],
  'api.common.nowDate': [
    [ new Date('2014-12-12 12:30:15.150'), '2014-12-12' ],
    [ new Date('2014-12-12 12:30:15'),     '2014-12-12' ],
    [ new Date('2014-12-12 12:30'),        '2014-12-12' ],
    [ new Date('2014-12-12'),              '2014-12-12' ],
  ],
  'api.common.nowDateTime': [
    [ new Date('2014-12-12 12:30:15.150Z'), '2014-12-12 12:30' ],
    [ new Date('2014-12-12 12:30:15Z'),     '2014-12-12 12:30' ],
    [ new Date('2014-12-12 12:30Z'),        '2014-12-12 12:30' ],
    [ new Date('2014-12-12Z'),              '2014-12-12 00:00' ],
  ],
  'api.common.spinalToCamel': [
    [ 'hello-world',     'helloWorld' ],
    [ 'hello_world',     'helloWorld' ],
    [ 'one-two-three',  'oneTwoThree' ],
    [ 'one_two_three',  'oneTwoThree' ],
    [ 'OneTwoThree',    'OneTwoThree' ],
    [ 'oneTwoThree',    'oneTwoThree' ],
    [ 'hello',                'hello' ],
    [ 'h',                        'h' ],
    [ '-',                         '' ],
    [ '_',                         '' ],
    [ '',                          '' ],
  ],
  'api.common.duration': [
    [ '1d',             86400000 ],
    [ '10h',            36000000 ],
    [ '7m',               420000 ],
    [ '13s',               13000 ],
    [ '2d 43s',        172843000 ],
    [ '5d 17h 52m 1s', 496321000 ],
    [ '1s',                 1000 ],
    [ 500,                   500 ],
    [ 0,                       0 ],
    [ '',                      0 ],
    [ '15',                    0 ],
    [ '10q',                   0 ],
    [ null,                    0 ],
    [ undefined,               0 ],
  ],
  'api.common.ip2int': [
    [ '127.0.0.1',        2130706433 ],
    [ '10.0.0.1',          167772161 ],
    [ '192.168.1.10',    -1062731510 ],
    [ '165.225.133.150', -1511946858 ],
    [ '0.0.0.0',                   0 ],
    [ 'wrong-string',           null ],
    [ '',                 2130706433 ],
  ],
  'api.net.isIP': [
    [ '127.0.0.1',         4 ],
    [ '10.0.0.1',          4 ],
    [ '192.168.1.10',      4 ],
    [ 'domain.com',        0 ],
    [ '127.0.0.com',       0 ],
    [ '',                  0 ],
  ],
  'api.common.escapeRegExp': [
    [ '/path/to/res?search=this.that&a=b', '\\\\/path\\\\/to\\\\/res\\\\?search=this\\\\.that&a=b' ],
    [ '/path/to/res?search=this.that',         '\\\\/path\\\\/to\\\\/res\\\\?search=this\\\\.that' ],
    [ '/path/to/res?search',                                 '\\\\/path\\\\/to\\\\/res\\\\?search' ],
    [ '/path/to/res',                                                   '\\\\/path\\\\/to\\\\/res' ],
    [ '/path',                                                                         '\\\\/path' ],
  ],
  'api.common.addTrailingSlash': [
    [ '/path',   '/path/' ],
    [ '/path/',  '/path/' ],
    [ '/',            '/' ],
    [ '',             '/' ],
  ],
  'api.common.stripTrailingSlash': [
    [ '/path',   '/path' ],
    [ '/path/',  '/path' ],
    [ '/',            '' ],
    [ '',             '' ],
  ],
  'api.common.dirname': [
    [ '/path/dir/',   '/path/' ],
    [ '/path/dir',    '/path/' ],
    [ '/path/',            '/' ],
    [ '/path',             '/' ],
    [ '/',                 '/' ],
    [ '',                 './' ],
  ],
  'api.common.bytesToSize': [
    [                         0, '0'      ],
    [                         1, '1'      ],
    [                       100, '100'    ],
    [                       999, '999'    ],
    [                      1000, '1 Kb'   ],
    [                      1023, '1 Kb'   ],
    [                      1024, '1 Kb'   ],
    [                      1025, '1 Kb'   ],
    [                      1111, '1 Kb'   ],
    [                      2222, '2 Kb'   ],
    [                     10000, '10 Kb'  ],
    [                   1000000, '1 Mb'   ],
    [                 100000000, '100 Mb' ],
    [               10000000000, '10 Gb'  ],
    [             1000000000000, '1 Tb'   ],
    [           100000000000000, '100 Tb' ],
    [         10000000000000000, '10 Pb'  ],
    [       1000000000000000000, '1 Eb'   ],
    [     100000000000000000000, '100 Eb' ],
    [   10000000000000000000000, '10 Zb'  ],
    [ 1000000000000000000000000, '1 Yb'   ],
  ],
  'api.common.sizeToBytes': [
    [        0,                         0 ],
    [      '0',                         0 ],
    [      '1',                         1 ],
    [      512,                       512 ],
    [    '100',                       100 ],
    [    '999',                       999 ],
    [   '1 Kb',                      1000 ],
    [   '2 Kb',                      2000 ],
    [  '10 Kb',                     10000 ],
    [   '1 Mb',                   1000000 ],
    [ '100 Mb',                 100000000 ],
    [  '10 Gb',               10000000000 ],
    [   '1 Tb',             1000000000000 ],
    [ '100 Tb',           100000000000000 ],
    [  '10 Pb',         10000000000000000 ],
    [   '1 Eb',       1000000000000000000 ],
    [ '100 Eb',     100000000000000000000 ],
    [  '10 Zb',   10000000000000000000000 ],
    [   '1 Yb', 1000000000000000000000000 ],
  ],
  'api.common.sizeToBytes.units': [
    [ function(obj) { return Object.keys(obj).length === 8; } ],
  ],
  'api.common.random': [
    [  0, 10, function(result) { return (result >=  0 && result <= 10); } ],
    [  1, 10, function(result) { return (result >=  1 && result <= 10); } ],
    [ -1, 10, function(result) { return (result >= -1 && result <= 10); } ],
    [ 10, 0,  function(result) { return (result >=  0 && result <= 10); } ],
    [ 10, 10, 10 ],
  ],
  'api.common.shuffle': [
    [ [1,2,3],   function(result) { return JSON.stringify(result.sort()) === '[1,2,3]'; }   ],
    [ ['a','b'], function(result) { return JSON.stringify(result.sort()) === '["a","b"]'; } ],
    [ [1,'a',3], function(result) { return JSON.stringify(result.sort()) === '[1,3,"a"]'; } ],
    [ [],        function(result) { return JSON.stringify(result.sort()) === '[]'; }        ],
  ],
  'api.common.extend': [
    [ { f1:1 },                 { f1:1 } ],
    [ { f1:1 }, {},             { f1:1 } ],
    [ {}, {},                         {} ],
    [ {}, null,                       {} ],
    [ { f1:1 }, { f2:2 }, { f1:1, f2:2 } ],
    [ [], { f2:2 },                   [] ],
    [ [], [],                         [] ],
    [ [], null,                       [] ],
    [ [], 'Hello', ['H','e','l','l','o'] ],
    [ null, null,                   null ],
    [ null,                         null ],
    [ null, {},                     null ],
  ],
  'api.common.clone': [
    [ {}, {} ],
    [ [], [] ],
    [ null, null ],
    [ { f1:1 }, { f1:1 } ],
    [ { f1:1 }, { f2:2 }, { f1:1, f2:2 } ],
    [ { f1:1, sub: { f2:2, a1:[1,2] } }, { f1:1, sub:{ f2:2, a1:[1,2] } } ],
    [ { f1:1, sub: { f2:2, a1:[1,2] } }, { f3:3, a2:[3,4] }, { f1:1, sub:{ f2:2, a1:[1,2] }, f3:3, a2:[3,4] } ],
  ],
  'api.common.trim': [
    [ 'abcdef',             'abcdef' ],
    [ 'abcdef   ',          'abcdef' ],
    [ '   abcdef',          'abcdef' ],
    [ '   abcdef   ',       'abcdef' ],
    [ ' a b c d e f ', 'a b c d e f' ],
  ],
  'api.common.ltrim': [
    [ 'abcdef',              'abcdef' ],
    [ 'abcdef   ',        'abcdef   ' ],
    [ '   abcdef',           'abcdef' ],
    [ '   abcdef   ',     'abcdef   ' ],
    [ ' a b c d e f ', 'a b c d e f ' ],
  ],
  'api.common.rtrim': [
    [ 'abcdef',              'abcdef' ],
    [ 'abcdef   ',           'abcdef' ],
    [ '   abcdef',        '   abcdef' ],
    [ '   abcdef   ',     '   abcdef' ],
    [ ' a b c d e f ', ' a b c d e f' ],
  ],
  'api.common.capitalize': [
    [ 'abc', 'Abc' ],
    [ 'Abc', 'Abc' ],
    [ 'aBC', 'Abc' ],
    [ 'ABC', 'Abc' ],
    [ 'a',     'A' ],
    [ ' bc', ' Bc' ],
    [ ' ',     ' ' ],
    [ '',       '' ],
    [ '+',     '+' ],
  ],
  'api.common.lpad': [
    [ 'abc', ' ', 10, '       abc' ],
    [ 'abc', '+',  4,       '+abc' ],
    [ 'abc', '+',  1,        'abc' ],
    [ 'abc', '+',  0,        'abc' ],
    [ 'abc', '+', -1,        'abc' ],
  ],
  'api.common.rpad': [
    [ 'abc', ' ', 10, 'abc       ' ],
    [ 'abc', '+',  4,       'abc+' ],
    [ 'abc', '+',  1,        'abc' ],
    [ 'abc', '+',  0,        'abc' ],
    [ 'abc', '+', -1,        'abc' ],
  ],
  'api.common.between': [
    [ 'abcdefghijk', 'cd', 'h',     'efg' ],
    [ 'field="value"', '"', '"',  'value' ],
    [ 'field:"value"', '"', '"',  'value' ],
    [ 'field[value]', '[', ']',   'value' ],
    [ 'kjihgfedcba', 'cd', 'h',        '' ],
    [ 'kjihgfedcba', 'dc', 'h',        '' ],
    [ 'field="value"', '=', '=',       '' ],
    [ 'field[value]', '{', '}',        '' ],
    [ '{a:"b",c:"d"}', '"', '"',      'b' ],
  ],
  'api.common.isScalar': [
    [ 'value1', true  ],
    [ 50,       true  ],
    [ true,     true  ],
    [ null,     false ],
    [ [],       false ],
    [ {},       false ],
    [ '',       true  ],
  ],
  'api.common.inArray': [
    [ [1, 2, 3], 1,                         true ],
    [ [1, 2, 3], 4,                        false ],
    [ ['e1', 'e2', 'e3'], 'e3',             true ],
    [ ['e1', 'e2', 'e3'], 'e4',            false ],
    [ [1, null, 3], null,                   true ],
    [ undefined, 'aaa',                    false ],
    [ null, 'aaa',                         false ],
    [ ['e1', 'e2', undefined ], undefined,  true ],
    [ ['e1', 'e2', null], null,             true ],
    [ ['e1', 'e2', 'e3'], undefined,       false ],
    [ ['e1', 'e2', 'e3'], null,            false ],
  ],
  'api.common.merge': [
    [ ['a', 'b'], ['a', 'c'],       ['a', 'b', 'c'] ],
    [ ['a', 'b'], ['a', 'b'],            ['a', 'b'] ],
    [ ['b', 'c'], ['a', 'b'],       ['b', 'c', 'a'] ],
    [ ['a', 'b'], ['c', 'd'], ['a', 'b' , 'c', 'd'] ],
    [ [1, 2, 3],  [1, 2, 3],              [1, 2, 3] ],
    [ [1, 2, 3],  [4, 5, 1],        [1, 2, 3, 4, 5] ],
  ],
  'api.common.override': [
    [
      methodConteiner,
      function method(obj) {
        obj.data++;
        return method.inherited(obj);
      },
      undefined
    ]
  ],
  'api.common.startsWith': [
    [ 'abc', 'a',   true  ],
    [ 'abc', 'b',   false ],
    [ 'abc', 'c',   false ],
    [ 'abc', ' ',   false ],
    [ 'abc', '+',   false ],
    [ 'abc', '' ,   true  ],
    [ 'abc', 'abc', true  ],
  ],
  'api.common.endsWith': [
    [ 'abc', 'a',   false ],
    [ 'abc', 'b',   false ],
    [ 'abc', 'c',   true  ],
    [ 'abc', ' ',   false ],
    [ 'abc', '+',   false ],
    [ 'abc', '' ,   true  ],
    [ 'abc', 'abc', true  ],
  ],
  'api.common.contains': [
    [ 'abc', 'a',     true  ],
    [ 'abc', 'b',     true  ],
    [ 'abc', 'c',     true  ],
    [ 'abc', 'ab',    true  ],
    [ 'abc', 'bc',    true  ],
    [ 'abc', 'abc',   true  ],
    [ 'abc', 'ac',    false ],
    [ 'abc', ' ',     false ],
    [ 'abc', 'abcde', false ],
    [ 'abc', '+',     false ],
    [ 'abc', '',      true  ],
  ],
  'api.common.range': [
    [ 1, 5,  [1, 2, 3, 4, 5] ],
    [ 8, 9,           [8, 9] ],
  ]
});
