({
  caption: { type: 'string', required: false },
  description: { type: 'string', required: false },
  access: '?Access',
  parameters: '?Schema',
  validate: '?Function',
  timeout: { type: 'number', required: false },
  queue: '?QueueParameters',
  serializer: '?Serializer',
  protocols: '?Protocols',
  deprecated: { type: 'boolean', required: false },
  method: 'AsyncFuction',
  returns: '?Schema',
  assert: '?Function',
  script: '?Function',
  examples: '?Example',
  application: '?Application',
});
