({
  caption: { type: 'string', required: false },
  description: { type: 'string', required: false },
  access: { type: 'Access', required: false },
  parameters: { type: 'Schema', required: false },
  validate: { type: 'function', required: false },
  timeout: { type: 'number', required: false },
  queue: { type: 'QueueParameters', required: false },
  serializer: { type: 'Serializer', required: false },
  protocols: { array: 'Protocols', required: false },
  deprecated: { type: 'boolean', required: false },
  method: 'AsyncFuction',
  returns: { type: 'Schema', required: false },
  assert: { type: 'function', required: false },
  script: { type: 'function', required: false },
  examples: { array: 'Example', required: false },
  application: { type: 'Application', required: false },
});
